id: AD789898E
base_file: fF606.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:22:32.253764
  last_modified_at: 2022-05-30 18:22:32.253770
