id: AD789898E
base_file: f1BA8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:22:32.244139
  last_modified_at: 2022-05-30 18:22:32.244147
