id: AD789898E
base_file: f48E6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:22:32.247241
  last_modified_at: 2022-05-30 18:22:32.247244
