id: AD789898E
base_file: fDB18.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:22:32.249459
  last_modified_at: 2022-05-30 18:22:32.249465
